-- ALIAS BIR TABLOYA KISALTMA VERME ISLEMIDIR
SELECT U.USERNAME_,U.NAMESURNAME,U.EMAIL,U.TELNR1,U.TELNR2,
C.CITY,
T.TOWN,
D.DISTRICT,
A.ADDRESSTEXT
FROM USER_ U 
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
WHERE U.ID=1
-- tablolara TOWN T gibi kisaltmalar yaptik ; ayni sekilde column'lara da U.USERNAME_ KULLANICIADI yapabilirdik.