--herhangi bir kullanicinin kac tane adresi var ona bakalim AMA BU SEFER ADRESLERIN SEHIRLERINE DE BAKALIM.

SELECT U.USERNAME_ AS KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,
U.TELNR1 AS TELEFON1,
U.TELNR2 AS TELEFON2,
COUNT(A.ID) AS ADRESSAYISI, -- AGGREGATE FUNCTION OLARAK COUNT KULLANDIGIM ICIN ASAGIDA GROUPBY YAPMAM GEREKIYOR.
COUNT(DISTINCT C.CITY) AS SEHIRSAYISI -- ### BURASI EKLENDI ########
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
GROUP BY U.USERNAME_,U.NAMESURNAME,U.TELNR1,U.TELNR2 -- group by'da alias i sileriz, aliasli hali calismaz.
ORDER BY COUNT(A.ID) DESC
-- sadece 1 adres girenleri isteseydim:
-- ORDER BY COUNT(A.ID) DESC yerine HAVING COUNT(A.ID)=1 dicektim.

-- ADRES SAYISI VE SEHIR SAYISI FARKLI OLSUN DESEYDIM : 
-- ORDER BY COUNT(A.ID) DESC yerine HAVING COUNT(A.ID)<>COUNT(DISTINCT C.CITY) dicektim.