-- hangi sehirde kac tane kullanici var

SELECT C.CITY AS SEHIR,
COUNT(U.ID) AS KULLANICISAYISI -- AGGREGATE FUNCTION OLARAK COUNT KULLANDIGIM ICIN ASAGIDA GROUPBY YAPMAM GEREKIYOR.
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
GROUP BY C.CITY
ORDER BY 2 DESC

-- sadece 1 adres girenleri isteseydim:
-- ORDER BY COUNT(A.ID) DESC yerine HAVING COUNT(A.ID)=1 dicektim.