--EN COK SATIS YAPILAN URUN KATEGORILERI

--siparis kesin olarak yapilmis olsun ve sonucumuz dogru ciksin diye ORDER_ tablosu uzerýnden gittik.
SELECT
I.CATEGORY1,I.CATEGORY2,
SUM(OD.TOTALPRICE) AS TOTAL
FROM ITEM I 
INNER JOIN ORDERDETAIL OD ON OD.ITEMID=I.ID
INNER JOIN ORDER_ O ON O.ID=OD.ORDERID
GROUP BY I.CATEGORY1,I.CATEGORY2
ORDER BY SUM(OD.TOTALPRICE) DESC
