-- EN COK SATIS YAPILAN 20 MUSTERI

SELECT TOP 20
U.NAMESURNAME,U.USERNAME_,
SUM(BD.TOTAL) AS TOTAL
FROM
USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID

GROUP BY U.NAMESURNAME,U.USERNAME_
ORDER BY SUM(BD.TOTAL) DESC