--BIR KULLANICININ YAPTIGI ALISVERIS SAYISI, ADEDI VE TOPLAM TUTARI

SELECT U.NAMESURNAME AD_SOYAD,
COUNT(DISTINCT B.ID) ALISVERIS_SAYISI,
COUNT(BD.ID) ALDIGI_URUN_SAYISI,
SUM(BD.AMOUNT) ALDIGI_URUN_MIKTARI,
SUM(TOTAL) TOPLAM_TUTAR
FROM USER_ U

INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ITEMID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID
INNER JOIN DISTRICT D ON D.ID=A.DISTRICTID
INNER JOIN INVOICE INV ON INV.ORDERID=O.ID

GROUP BY U.NAMESURNAME