--maas ortalamasý 5.500'den fazla olan departmanlari listele.
--DEPARTMENT,AVGSALARY

SELECT 
D.DEPARTMENT,
ROUND(AVG(P.SALARY),2) AS AVG_SALARY

FROM DEPARTMENT D
INNER JOIN PERSON P ON P.DEPARTMENTID=D.ID
GROUP BY D.DEPARTMENT
HAVING ROUND(AVG(P.SALARY),2)>5500
ORDER BY 2 DESC