--herbir pozisyonda mevcut halde calisanlar olarak kac kisi ve ortalama maaslarinin ne kadar oldugunu listelettir.
-- POSITION,PERSONCOUNT,AVG_SALARY

--INNER JOIN ILE

SELECT POS.POSITION,
COUNT(POS.ID) PERSONCOUNT,
ROUND(AVG(PER.SALARY),2) AVG_SALARY
FROM POSITION POS
INNER JOIN PERSON PER ON PER.POSITIONID=POS.ID
GROUP BY POS.POSITION
ORDER BY POS.POSITION	