--yillara göre ise alinan personel sayisini kadin ve erkek bazinda listelettir.
--YEAR,MALE_PERSON,FEMALE_PERSON

SELECT * FROM PERSON
---------------------
--yillara bakalim.
SELECT DISTINCT YEAR(P.INDATE) AS YEARS_,
(SELECT COUNT(*) FROM PERSON WHERE GENDER='E' AND YEAR(INDATE)=YEAR(P.INDATE)) AS MALE_PERSONCOUNT,
(SELECT COUNT(*) FROM PERSON WHERE GENDER='K' AND YEAR(INDATE)=YEAR(P.INDATE)) AS FEMALE_PERSONCOUNT
FROM PERSON P
ORDER BY 1


