--herbir personelin ne kadar zamandir calistigini ay olarak getir.
-- PERSON,INDATE,OUTDATE,WORKINGTIME
SELECT P.NAME_+' '+P.SURNAME AS PERSON_,
P.INDATE,
P.OUTDATE,

CASE 
	WHEN OUTDATE IS NOT NULL THEN DATEDIFF(MONTH,INDATE,OUTDATE)
	ELSE DATEDIFF(MONTH,INDATE,GETDATE())
END AS WORKINGTIME,

CASE 
	WHEN OUTDATE IS NOT NULL THEN 'ISTEN AYRILDI'
	ELSE 'DEVAM EDIYOR'
END AS WORKINGSTATUS
FROM PERSON P 
ORDER BY WORKINGTIME DESC