--AGEGROUP olusturup yas araliklarina boldugumuz column'da kac kisi oldugunu getir.
-- Ornek : 20-35 yas 45 kisi gibi.
-- AGEGROUP alanini kullanmadan sorguyu getir.

SELECT AGEGROUP,
COUNT(*) FROM CUSTOMERS AS CUSTOMERCOUNT 
GROUP BY AGEGROUP,
ORDER BY AGEGROUP

--kolayca yukardaki gibi yapabiliriz ama bu AGEGROUP alaninin olmadigini dusunelim.

SELECT
CASE 
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAS ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '20-35 YAS ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '20-35 YAS ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '20-35 YAS ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE())> 65 THEN '+ 65 YAS'
END AGEGROUP, -- end'den sonra column ismi girilir.
COUNT(*) AS CUSTOMERCOUNT
FROM CUSTOMERS
GROUP BY --group by'a AGEGROUP diye direkt giremiyorum cunku bu column havada asili. O yuzden tekrar uzunca yazmam gerek.
CASE      -- havada kalmamasi icin exmp9-1'de bunu yapalim.(DynamicView)
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAS ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '20-35 YAS ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '20-35 YAS ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '20-35 YAS ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE())> 65 THEN '+ 65 YAS'
END

ORDER BY AGEGROUP