--HANGI SEHIRDE KAC KADIN KAC ERKEK OLDUGUNU,
-- SEHIR ADI, ERKEKSAYISI,KADINSAYISI OLARAK GÝR.

SELECT CITY AS SEHIRADI,
(SELECT COUNT(*) FROM CUSTOMERS C WHERE CITYID=CT.ID) AS CUSTOMERCOUNT,
(SELECT COUNT(*) FROM CUSTOMERS C WHERE CITYID=CT.ID AND GENDER='E') AS ERKEKSAYISI,
(SELECT COUNT(*) FROM CUSTOMERS C WHERE CITYID=CT.ID AND GENDER='K') AS KADINSAYISI
FROM CITIES CT
ORDER BY CUSTOMERCOUNT DESC


