-- Telefon numarasina gore operator bilgisi getirmek istiyoruz.
-- 50 ya da 55 icin X operatoru,
-- 54 ile baslayanlar Y operatoru,
-- 53 Z operatoru.
-- Hangi operatorden kac kisi var onu da sorgulat.

SELECT CUSTOMERNAME,TELNR1,TELNR2, 
TELNR1_XOPERATORCOUNT + TELNR2_XOPERATORCOUNT AS XOPERATORCOUNT,
TELNR1_YOPERATORCOUNT + TELNR2_YOPERATORCOUNT AS YOPERATORCOUNT,
TELNR1_ZOPERATORCOUNT + TELNR2_ZOPERATORCOUNT AS ZOPERATORCOUNT
FROM
(
SELECT

CASE
	WHEN TELNR1 LIKE '(50%' OR TELNR1 LIKE '(55%' THEN 1
	ELSE 0
END AS TELNR1_XOPERATORCOUNT

CASE
	WHEN TELNR1 LIKE '(54%' THEN 1
	ELSE 0
END AS TELNR1_YOPERATORCOUNT

CASE
	WHEN TELNR1 LIKE '(53%' THEN 1
	ELSE 0
END AS TELNR1_ZOPERATORCOUNT
------------
CASE
	WHEN TELNR2 LIKE '(50%' OR TELNR2 LIKE '(55%' THEN 1
	ELSE 0
END AS TELNR2_XOPERATORCOUNT

CASE
	WHEN TELNR2 LIKE '(54%' THEN 1
	ELSE 0
END AS TELNR2_YOPERATORCOUNT

CASE
	WHEN TELNR2 LIKE '(53%' THEN 1
	ELSE 0
END AS TELNR2_ZOPERATORCOUNT
* FROM CUSTOMERS 