-- ISTANBULDA YASAYAN KISILERI JOIN KULLANARAK GETIR.
SELECT 
C.*, CT.CITY
FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID=C.CITYID
WHERE CT.CITY='ÝSTANBUL'

--ISTANBULDA YASAYAN KISILERI SUBQUERY KULLANARAK GETIR.
SELECT 
(SELECT CITY FROM CITIES WHERE ID=C.CITYID),
* FROM CUSTOMERS C
WHERE
(SELECT CITY FROM CITIES WHERE ID=C.CITYID)='ÝSTANBUL'

--YA DA
SELECT 
(SELECT CITY FROM CITIES WHERE ID=C.CITYID),
* FROM CUSTOMERS C
WHERE C.CITYID
IN (SELECT ID FROM CITIES WHERE CITY='ÝSTANBUL')

--ISTANBUL VE ANKARA DESEYDI
SELECT 
(SELECT CITY FROM CITIES WHERE ID=C.CITYID),
* FROM CUSTOMERS C
WHERE C.CITYID
IN (SELECT ID FROM CITIES WHERE CITY IN ('ÝSTANBUL','ANKARA'))
