-- Hangi operatorden kac kisi var onu da sorgulat.
SELECT 
SUM(TELNR1_XOPERATORCOUNT + TELNR2_XOPERATORCOUNT) AS XOPERATORCOUNT,
SUM(TELNR1_YOPERATORCOUNT + TELNR2_YOPERATORCOUNT) AS YOPERATORCOUNT,
SUM(TELNR1_ZOPERATORCOUNT + TELNR2_ZOPERATORCOUNT) AS ZOPERATORCOUNT
FROM
(
SELECT

CASE
	WHEN TELNR1 LIKE '(50%' OR TELNR1 LIKE '(55%' THEN 1
	ELSE 0
END AS TELNR1_XOPERATORCOUNT

CASE
	WHEN TELNR1 LIKE '(54%' THEN 1
	ELSE 0
END AS TELNR1_YOPERATORCOUNT

CASE
	WHEN TELNR1 LIKE '(53%' THEN 1
	ELSE 0
END AS TELNR1_ZOPERATORCOUNT
------------
CASE
	WHEN TELNR2 LIKE '(50%' OR TELNR2 LIKE '(55%' THEN 1
	ELSE 0
END AS TELNR2_XOPERATORCOUNT

CASE
	WHEN TELNR2 LIKE '(54%' THEN 1
	ELSE 0
END AS TELNR2_YOPERATORCOUNT

CASE
	WHEN TELNR2 LIKE '(53%' THEN 1
	ELSE 0
END AS TELNR2_ZOPERATORCOUNT
* FROM CUSTOMERS 