--istanbulda olup ilcesi kadikoy disindakileri listele.

--JOIN ILE
SELECT * FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID=C.CITYID
INNER JOIN DISTRICTS D ON D.ID=C.DISTRICTID
WHERE CT.CITY='ÝSTANBUL' AND D.DISTRICT<>'KADIKÖY' -- esit degildir : <>
--ya da WHERE CT.CITY='ÝSTANBUL' AND D.DISTRICT NOT LIKE 'KADIKÖY'
--ya da WHERE CT.CITY='ÝSTANBUL' AND D.DISTRICT NOT IN('KADIKÖY')
--ya da WHERE CT.CITY='ÝSTANBUL' AND NOT D.DISTRICT='KADIKÖY'


--SUBQUERY ILE
SELECT * FROM CUSTOMERS 
WHERE CITYID IN (SELECT ID FROM CITIES WHERE CITY='ÝSTANBUL')
AND DISTRICTID NOT IN (SELECT ID FROM DISTRICTS WHERE DISTRICT='KADIKÖY')
