--HANGI SEHIRDE KAC ERKEK KAC KADIN OLDUGU,
-- TABLO SIRASI : CITY, GENDER, CUSTOMERCOUNT

SELECT CT.CITY,C.GENDER,
COUNT(C.ID) AS CUSTOMERCOUNT
FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID=C.CITYID
GROUP BY CT.CITY,C.GENDER
HAVING COUNT(C.ID)>=10 --WHERE COUNT(C.ID)>=10 olmaz, cunku istenen sart COUNT'lu, yani aggregate function o yuzden HAVING.
ORDER BY CUSTOMERCOUNT DESC ,C.GENDER

