--Her ilde en cok musteriye sahip olan ilceleri coktan aza dogru sirala.

SELECT CT.CITY,D.DISTRICT,COUNT(C.ID) AS CUSTOMERCOUNT
FROM CUSTOMERS C
INNER JOIN CITIES CT CT.ID=C.CITYID
INNER JOIN DISTRICTS D D.ID=C.DISTRICTID
GROUP BY CT.CITY,D.DISTRICT
ORDER BY CT.CITY,COUNT(C.ID) DESC

