SELECT U.ID,U.NAMESURNAME,
COUNT(B.ID) AS BASKETCOUNT, 
MIN(B.CREATEDDATE) AS FIRSTBASKETDATE,
MAX(B.CREATEDDATE) AS LASTBASKETDATE,
SUM(BD.TOTAL) AS TOTAL,
COUNT(BD.ID) AS ITEMCOUNT_
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
GROUP BY U.ID,U.NAMESURNAME
ORDER BY SUM(BD.TOTAL) DESC