--her sehirde en cok satis yapilan 3 kategoriyi 
-- ve onun altinda en cok satis yapilan 3 alt kategoriyi getir.
-- CITY,CATEGORY1,CATEGORY2,TOTALSALE

SELECT S.CITY,S1.CATEGORY1,S2.CATEGORY2,
SUM(S1.TOTALSALE) AS TOTALSALE
FROM SALEORDERS S

CROSS APPLY
(
SELECT TOP 3 CATEGORY1,SUM(LINETOTAL) AS TOTALSALE 
FROM SALEORDERS 
WHERE CITY=S.CITY 
GROUP BY CATEGORY1
ORDER BY 2 DESC
) S1

CROSS APPLY
(
SELECT TOP 3 CATEGORY2,SUM(LINETOTAL) AS TOTALSALE 
FROM SALEORDERS 
WHERE CITY=S.CITY AND CATEGORY1=S1.CATEGORY1 
GROUP BY CATEGORY2
ORDER BY 2 DESC
) S2

GROUP BY CITY,S1.CATEGORY1,S2.CATEGORY2
ORDER BY 1,2,4 DESC