--her ilin en cok satan ilk 5 kategorisini 
--CITY,CATEGORY1,TOTALSALE olarak getir.

SELECT 
S.CITY,
S1.CATEGORY1,
SUM(S1.TOTALSALE) AS TOTALSALE --bu SUM baska bir SQL'in icerisinden hesaplanarak gelmeli. 
                               -- O yuzden CROSS APPLY yaptik. 

FROM SALEORDERS S
CROSS APPLY
(
SELECT TOP 5 CATEGORY1,
SUM(LINETOTAL) AS TOTALSALE 
FROM SALEORDERS 
WHERE CITY=S.CITY 
GROUP BY CATEGORY1
ORDER BY 2 DESC
) S1


GROUP BY S.CITY,S1.CATEGORY1
ORDER BY S.CITY,SUM(S1.TOTALSALE) DESC
